### PR TITLE
MICRO-150: Graphql mesh server

### PR DESCRIPTION
**Pull request by TheOrangePuff**
**Description of the proposed changes**  

* Adds graphql-mesh-hosting construct

**Notes to PR author**

⚠️ Please make sure the changes adhere to the guidelines mentioned [here](https://aligent.atlassian.net/wiki/spaces/AL/pages/2728919167/Pull+Request+guidelines)

**Notes to reviewers**  

🛈  When you've finished leaving feedback, please add a final comment to the PR tagging the author, letting them know that you have finished leaving feedback

### CODE REVIEW

**Comment by krishanthisera** [comment]
@TheOrangePuff I think you would needf to pull the latest changes from the `main` branch, which would fix the build issue.

Cheers :clinking_glasses:

**Review by krishanthisera — CHANGES_REQUESTED** [review]
I think we would need to pull the latest changes from the main branch, which would fix the build issue.

**Comment by AdamJHall** [comment]
> I think we would need to pull the latest changes from the main branch, which would fix the build issue.

Pulling in main created a whole bunch of merge conflicts, but I was able to just update the calls to the `Bundling` utility which fixed the issue instead.

**Review by AdamJHall — APPROVED** [review]

**Review by krishanthisera — APPROVED** [review]
All good :clinking_glasses:

**Pull request merged**
